# Don't print a new line at the start of the prompt
add_newline = true 

# Make prompt a single line instead of two lines
[line_break]
disabled = false 

[character]                        
#success_symbol = "[λ](bold green)"  
success_symbol = "[✗](bold green)"  
error_symbol = "[✗](bold red) "

# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

